# greet 
print("HELLO, WELCOME")

# list of player
l=["AJINKYA RAHANE","CHETESHWAR PUJARA","HANUMA VIHARI","ROHIT SHARMA","SHUBMAN GILL","VIRAT KOHALI","RAVICHANDRAN ASHWIN","RAVINDRA JADEJA","RISHABH PANT","WRIDDHIMAN SAHA","ISHANT SHARMA","JASPIT BUMRAh","MOHAMMED SHAMI","MOHAMMED SIRAJ","UMESH YADAV"]
print("INDIAN CRICKET PLAYER'S NAME LIST:")
print(l)

# accept player name
m=input("Enter A Cricket Player Name:\t")
n=m.upper()

# player details
country={"AJINKYA RAHANE":"INDIA","CHETESHWAR PUJARA":"INDIA","HANUMA VIHARI":"INDIA","ROHIT SHARMA":"INDIA","SHUBMAN GILL":"INDIA","VIRAT KOHALI":"INDIA","RAVICHANDRAN ASHWIN":"INDIA","RAVINDRA JADEJA":"INDIA","RISHABH PANT":"INDIA","WRIDDHIMAN SAHA":"INDIA","ISHANT SHARMA":"INDIA","JASPIT BUMRAH":"INDIA","MOHAMMED SHAMI":"INDIA","MOHAMMED SIRAJ":"INDIA","UMESH YADAV":"INDIA"}
teams={"AJINKYA RAHANE":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","RAJASTAN ROYALS","WEST ZONE","NORTH MUMBAI PANTHERS"],"CHETESHWAR PUJARA":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","CHENNAI SUPER KINGS","MUMBAI A"],"HANUMA VIHARI":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","SUNRISE HYDRABAD","HYDRABAD"],"ROHIT SHARMA":["INDIA","INDIA A","INDIA RED","INDIA UNDER-19","MUMBAI INDIANS","MUMBAI"],"SHUBMAN GILL":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","KOLKATA KNIGHT RIDERS","PUNJAB"],"VIRAT KOHALI":["INDIA","INDIA A","ASIA XI","INDIA UNDER-19","ROYAL CHALLENGERS BANGALORE","DELHI"],"RAVICHANDRAN ASHWIN":["INDIA","INDIA A","INDIA BLUE","INDIA UNDER-19","PUNJAB KINGS","PUNE SUPERGIANT"],"RAVINDRA JADEJA":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","CHENNAI SUPER KINGS","KOCHI TUSKERS KERALA"],"RISHABH PANT":["INDIA","INDIA A","ASIA XI","INDIA UNDER-19","DELHI CAPITALS(C)","DELHI"],"WRIDDHIMAN SAHA":["INDIA","INDIA A","INDIA BLUE","INDIA UNDER-19","SUNRISERS HYDRABAD","BENGAL"],"ISHANT SHARMA":["INDIA","INDIA A","INDIA BLUE","INDIA UNDER-19","SUNRISERS HYDRABAD","RISING PUNE SUPERGIANT"],"JASPIT BUMRAH":["INDIA","INDIA A","INDIA GREEN","INDIA UNDER-19","MUMBAI INDIANS","GUJRAT"],"MOHAMMED SHAMI":["INDIA","INDIA A","ASIA XI","INDIA UNDER-19","ICC WORLD XI","DELHI CAPITALS","BENGAL"],"MOHAMMED SIRAJ":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","REST OF INDIA","ROYAL CHALLENGER BANGALORE"],"UMESH YADAV":["INDIA","INDIA A","INDIA B","INDIA UNDER-19","DELHI CAPITALS","VIDARBHA"]}
series={"AJINKYA RAHANE":["TEST(VC)","ODI","T20","IPL","FC"],"CHETESHWAR PUJARA":["TEST","ODI","IPL","FC"],"HANUMA VIHARI":["TEST","ODI","IPL","FC"],"ROHIT SHARMA":["TEST","ODI","T20(VC)","IPL","FC"],"SHUBMAN GILL":["TEST","ODI","IPL","FC"],"VIRAT KOHALI":["TEST(C)","ODI(C)","T20(C)","IPL","FC"],"RAVICHANDRAN ASHWIN":["TEST","ODI","T20","IPL","FC"],"RAVINDRA JADEJA":["TEST","ODI","T20","IPL","FC"],"RISHABH PANT":["TEST","ODI","T20","IPL","FC"],"WRIDDHIMAN SAHA":["TEST","ODI","IPL","FC"],"ISHANT SHARMA":["TEST","ODI","T20","IPL","FC"],"JASPIT BUMRAH":["TEST","ODI","T20","IPL","FC"],"MOHAMMED SHAMI":["TEST","ODI","T20","IPL","FC"],"MOHAMMED SIRAJ":["TEST","ODI","T20","IPL","FC"],"UMESH YADAV":["TEST","ODI","T20","IPL","FC"]}
status={"AJINKYA RAHANE":"BATSMAN","CHETESHWAR PUJARA":"BATSMAN","HANUMA VIHARI":"BATSMAN","ROHIT SHARMA":"BATSMAN","SHUBMAN GILL":"BATSMAN","VIRAT KOHALI":"BATSMAN","RAVICHANDRAN ASHWIN":"BOWLER","RAVINDRA JADEJA":"ALL-ROUNDER","RISHABH PANT":"BATSMAN(WICCKTE-KEEPER)","WRIDDHIMAN SAHA":"BATSMAN(WICCKET-KEEPER)","ISHANT SHARMA":"BOWLER","JASPIT BUMRAH":"BOWLER","MOHAMMED SHAMI":"BOWLER","MOHAMMED SIRAJ":"BOWLER","UMESH YADAV":"BOWLER"}

# output
print("PLAYER NAME:\t",n)
print("COUNTRY:\t",country.get(n))
print("TEAMS:\t",teams.get(n))
print("SERIES:\t",series.get(n))
print("STATUS:\t",status.get(n))

# regards
print("Thanks")